DROP TABLE sku_info IF EXISTS;

CREATE TABLE sku_info (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  NAME varchar(100) NOT NULL,
  DATA_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
) ENGINE=InnoDB;